
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=yes
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='\[\e[1;32m\][\u@\h: ~\W] \$ \[\e[1;37m\]'
else
    PS1='\[\e[1;32m\][\u@\h: ~\W] \$ \[\e[1;37m\]'
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi


#alias make='make -j 4'

alias mat='/opt/matlab_2011a/bin/matlab -nodesktop -nosplash'
alias matlab='/opt/matlab_2011a/bin/matlab -nosplash'

alias Copy='/opt/copy/x86_64/CopyAgent'
alias CopyConsole='/opt/copy/x86_64/CopyConsole'

# set intel CC & MKL enviroments
. /opt/l_cc_11.0.083/setenv_intel_em64t.sh
. /opt/l_mkl_11.1.059/setenv_intel.sh intel64

# setup CUDA tk/sdk enviroments
. /opt/cuda-7.0/setenv.sh

# setup opencv-2.4.5
. /opt/opencv-2.4.5/setenv.sh

# setup ffmpeg-1.0
. /opt/ffmpeg-1.0/setenv.sh

# setup x264_130
. /opt/x264_130/setenv.sh

export LANG=C

export JAVA_HOME=/usr/lib/jvm/java-6-openjdk 
export PATH=$PATH:$JAVA_HOME/bin
export PATH=$PATH:$HOME/android-sdks/tools 
export PATH=$PATH:$HOME/android-sdks/platform-tools 

# setup lemon
. /opt/lemon/setenv.sh

#setup eigen3
. /opt/eigen3/setenv.sh

export PATH="/opt/Komodo-IDE-7/bin:$PATH"

TEXLIVE_DIR=/opt/texlive/texlive/2012

PATH=$TEXLIVE_DIR/bin/x86_64-linux:$PATH; export PATH
MANPATH=$TEXLIVE_DIR/texmf/doc/man:$MANPATH; export MANPATH
INFOPATH=$TEXLIVE_DIR/texmf/doc/info:$INFOPATH; export INFOPATH

# setup libconfig
. /opt/libconfig/setenv.sh

# setup cgal
. /opt/cgal/setenv.sh

# setup gtest
. /opt/gtest-1.7/setenv.sh
