CXX=g++

LIBS=-lprotobuf -lglog

all : 

simpleProtoDemo:
	$(CXX) -o $@ simpleProtoDemo.o simple_proto/simple.pb.o $(LIBS)
simpleProtoDemo.o:
	$(CXX) -c simpleProtoDemo.cpp
simple.pb.o:
	$(CXX) -c simple.pb.cc

clean:
	rm simpleProtoDemo.* simple_proto/simple.pb.o
simpleProtoDemo
