######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 20 20:10:51 2015
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += . .
INCLUDEPATH += .

CONFIG += release console #debug qt warn on
QMAKE_CXXFLAGS += -Wl,--no-as-needed -std=c++0x

# Input
HEADERS += Thread.h Thread.hpp
SOURCES += main.cpp

#LIBS = -pthread


