######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 10 11:37:53 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . .
INCLUDEPATH += .

# Input
HEADERS += flag_declare.h
SOURCES += gflagDemo.cpp
